тест: ср
	../../rus_asm/src/асм тест.асм тест
	xxd тест
	chmod +x тест
	./тест

ср:
	gcc -o ср main.c \
	gner.c gner_Асм_Linux_64.c gner_Fasm_Linux_64.c \
	pser.c pser_type.c pser_inst.c  pser_expr.c \
	tzer.c lsts.c
	chmod +x ср
	./ср
